services:
  holoocean:
    image: frostlab/holoocean:2.0-dev-ubuntu22.04-cuda12.4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holoocean
    runtime: nvidia
    user: ue4
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ../../client:/home/ue4/client  # Mount the client directory
      - ./build_cache/build:/home/ue4/client/build:rw   # Permissions fix for when holoocean is built inside and outside the container
      - ./build_cache/egg-info:/home/ue4/client/src/holoocean.egg-info:rw      # Permissions fix for when holoocean is built inside and outside the container
      - $HOME/.local/share/holoocean:/home/ue4/.local/share/holoocean  # Mount the local share directory for persistent world installation
      - ./entrypoint.sh:/home/ue4/entrypoint.sh  # Mount the entrypoint script
    entrypoint: /home/ue4/entrypoint.sh